name: Pull request

on: pull_request

jobs:
  add-to-project:
    name: Add PR to workers-sdk GH project
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST https://devprod-status-bot.devprod.workers.dev/pr-project/wrangler-action/${{ github.event.number }}
