name: Pull request

on: pull_request

jobs:
  add-to-project:
    name: Add PR to workers-sdk GH project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/cloudflare/projects/1
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}